<?php

namespace AppBundle\Repository;

/**
 * ApparatusStatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApparatusStatusRepository extends \Doctrine\ORM\EntityRepository
{
}
