<?php

namespace AppBundle\Repository;

/**
 * ApparatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApparatusRepository extends \Doctrine\ORM\EntityRepository
{
}
